### ISSUE TITLE
Add mongodb to dependencies

### ISSUE THREAD

**Issue by trainerbill** [jedireza/mongo-models#19]
Any reason why mongodb is not in the actual dependencies?  I am using the hapi module and don't think I should have to manually install mongo-models and mongodb

**Comment by jedireza** [comment]
It's a peer dependency: https://github.com/jedireza/mongo-models/blob/4deca139c79add15dccf4bc07ea26494219f4662/package.json#L36-L38

This gives consumers more fine grained control of their version of `mongodb`.
