### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by juvasquezg** [jedireza/mongo-models#20]
Hi,

I have seen frame and aqua (your projects), mongo-models supports "Promise" to use async-await syntax sugar?

Thank you!!

**Comment by jedireza** [comment]
This was brought up before we split this library apart from `hapi-mongo-models`. You can see that discussion here: https://github.com/jedireza/hapi-mongo-models/issues/6

**Comment by jedireza** [comment]
:mega: Async/await support is on the menu now. Tracked via: https://github.com/jedireza/mongo-models/issues/24 and help is very much appreciated.
