### ISSUE TITLE
MongoModels#aggregate does not pass test case

### ISSUE THREAD

**Issue by andyfry01** [jedireza/mongo-models#29]
Hi again!

As written, the [aggregate method](https://github.com/jedireza/mongo-models/blob/master/index.js#L243) does not pass [this test](https://github.com/jedireza/mongo-models/blob/master/test/index.js#L854). The method as written returns the AggregationCursor instead of the results array. 

I've got a small PR ready if you'd like to make the change.

Thanks,
Andy

**Comment by jedireza** [comment]
Are you getting a failure using the latest master and the mongdb 2.0 driver? With a fresh install I'm getting all tests passing.

**Comment by jedireza** [comment]
Also, this test is also passing on the upcoming async branch (see: #25) using the mongodb 3.x driver.

**Comment by andyfry01** [comment]
Hey @jedireza, after working on #27 I noticed that the tests weren't passing for that particular test, although that might just be something happening locally for me. If it's working for you after updating the mongodb driver then I'd imagine it's fine.
