### ISSUE TITLE
How to declare a view with mongo-models

### ISSUE THREAD

**Issue by mike123vn** [jedireza/mongo-models#32]
Mongodb from version 3.4 supported view feature, so how can i declare a view with Mongo-model

**Comment by jedireza** [comment]
I have not used views before. Below is just a guess based on what I read from the docs: https://docs.mongodb.com/manual/core/views/

> how can i declare a view with Mongo-model

You could probably use the `MongoDB.Db` we get back from `connect(...)`, and call `createView(...)` on it.

Once you've created a view it sounds like they'll work just like normal collections, only read only.
