### ISSUE TITLE
[Question] createIndexes guide

### ISSUE THREAD

**Issue by anhntbk08** [jedireza/mongo-models#33]
Hi,

Thank for your great work. I just wonder what is the best way to use createIndexes?

Can it be totally automatic when we defined model?

Cheers.

**Comment by jedireza** [comment]
Yeah you need to instrument that in your own app. The bigger your app gets the less likely you'd wan't to run an auto indexer when the app started.

[`hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models) actually does have an option that takes advantage of the `createIndexes` method.
