### ISSUE TITLE
Using dynamic schema

### ISSUE THREAD

**Issue by anhntbk08** [jedireza/mongo-models#34]
Hi there,

Thank for your great lib, one question here is how can i use dynamic schema? I want to use some important fields for indexing and set the constrain for the data otherwise i want to use remain as dynamic fields?
Is that possible?

Thanks.

**Comment by jedireza** [comment]
Maybe something like:

```
const schema = Joi.object({
    _id: Joi.object(),
    name: Joi.string().required(),
    dynamic: Joi.object()
});
```

**Comment by anhntbk08** [comment]
@jedireza this is not what i need, i need something like {strict: false} in mongoose?
Any other idea ?

**Comment by jedireza** [comment]
Nope. Probably just use mongoose.

**Comment by anhntbk08** [comment]
i should use Joi to validate the schema instead of using mongo-models does that

Thanks for your support
