### ISSUE TITLE
FR: upsert method

### ISSUE THREAD

**Issue by svnlto** [jedireza/mongo-models#4]
Would you be open to implementing and `upsert` functionality. Similar to https://github.com/pouchdb/upsert

**Comment by jedireza** [comment]
Thanks for creating an issue.

Both `updateOne` and `updateMany` accept an `upsert` boolean option. That's the functionality you're looking for right?

https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/
https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/

**Comment by svnlto** [comment]
Oh, should have read the docs.. Thanks for pointing that out to me. It's exactly what I was looking for.
