### ISSUE TITLE
Compatibility with @hapi/joi 17 

### ISSUE THREAD

**Issue by bmgdev** [jedireza/mongo-models#48]
Reza, anyone in process here on getting up to 17 or need a PR?

**Comment by jedireza** [comment]
Nope. A PR would be great! 🙏

**Comment by bmgdev** [comment]
K, we recently had to upgrade multiple Hapi backends but it wasn't much work as I recall.  @maratvmk could you submit a PR for Joi 17? Least we can do for you maintaining these repos for so long, thanks Reza.

**Comment by maratvmk** [comment]
@jedireza please check my PR https://github.com/jedireza/mongo-models/pull/50/files 
with Joi 17 and other package updates. All test passed

**Comment by jedireza** [comment]
Thanks folks. Published as `mongo-models@3.0.4`.
