### ISSUE TITLE
Support Promise

### ISSUE THREAD

**Issue by bubuzzz** [jedireza/mongo-models#6]
Currently, the result needs to be processed through callback. Is there any plan to support Promise in the near future to leverage the async/await ?

**Comment by jedireza** [comment]
Thanks for opening an issue. This was asked in `hapi-mongo-models` before I abstracted into `mongo-models`.

Please reference that old discussion here: https://github.com/jedireza/hapi-mongo-models/issues/6

**Comment by jedireza** [comment]
:mega: Async/await support is on the menu now. Tracked via: https://github.com/jedireza/mongo-models/issues/24 and help is very much appreciated.
