### ISSUE TITLE
Collection global prefix

### ISSUE THREAD

**Issue by mstduff** [jedireza/mongo-models#7]
not sure where would be best place to implement (here, hapi-mongo, frame, aqua)....

but it would be nice to be able to set an env/config to have a global collection prefix.

example:
```
// model
Kitten.collection = 'kittens';

//aqua config
hapiMongoModels: {
        mongodb: {
            uri: {
                $filter: 'env',
                production: process.env.MONGODB_URI,
                test: 'mongodb://devurl',
                $default: 'mongodb://devurl'
            }
        },
        autoIndex: true,
        prefix: 'aqua_'
    };
````
result collection would be 'aqua_kittens'

**Comment by jedireza** [comment]
Thanks for opening an issue.

My first thought is to put this in the model definitions. It wouldn't be a default, you'd have to instrument it per model, but the upside is that it's explicit.

```js
const Joi = require('joi');
const MongoModels = require('mongo-models');

class Customer extends MongoModels {}

Customer.collection = process.env.MONGO_COLLECTION_PREFIX + '_customers'; // here we go

Customer.schema = Joi.object().keys({
    name: Joi.string().required(),
    email: Joi.string().email(),
    phone: Joi.string()
});

module.exports = Customer;
```

**Comment by mstduff** [comment]
Thanks for the response!

I think thats acceptable, hopefully that is something you would consider adding to frame. For now I will alter the core models to meet my needs.

Thanks again
