### ISSUE TITLE
Extending models

### ISSUE THREAD

**Issue by shreyapandit** [jedireza/mongo-models#8]
Hi @jedireza 

Is there a way to extend and make new models from already constructed MongoModels? For example I already have a User Model, and now need to specialize the user and extend User to say, Professor (which would have it's own schema additions over user).

Is that possible currently? I tried to read through documentation but did not find anything in this regard.

Thanks in advance!

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Is there a way to extend and make new models from already constructed MongoModels?

I've never tried that. You could give it a shot and see what happens. 😁

I tend to think about model classes and mongodb collections as a 1:1 mapping. It seems like a slippery path to have inherited/nested class logic that maps to flat mongodb collections.

I've built a user system with users and roles, etc... maybe it could be a source of inspiration. Here is a relevant wiki article from that project:

 - https://github.com/jedireza/aqua/wiki/Users%2C-Roles-%26-Groups
 - https://github.com/jedireza/aqua/tree/master/server/models

I hope that helps. Good luck. Oh and please update this thread with any learning you think would be relevant to future readers.
