### ISSUE TITLE
options

### ISSUE THREAD

**Issue by rncortes1990** [jedireza/mongo-models#9]
Hi There, 
Im working with your API and im trying to call another collection from another folder, but i receive an error with the form "Cannot read property 'collection' of undefined". But I know collection is fine because Im using it from another API.

So I tried to use the mongo connect, and here is my question because it doesnt appear anything on the documentation.

What are the options for the connect method....

Thanks for your time :))

Greetings from Chile

**Comment by jedireza** [comment]
Thanks for opening an issue. Could you share a reproducible example?
